### ISSUE TITLE
Colour by column error

### ISSUE THREAD

**Issue by K-Meech** [platybrowser/platybrowser-fiji#59]
Since the update, when I click colour by column, it immediately errors with:

Exception in thread "Thread-20" java.lang.NullPointerException
	at de.embl.cba.tables.Tables.getColumnNamesAsArray(Tables.java:552)
	at de.embl.cba.tables.color.ColumnColoringModelCreator.showDialog(ColumnColoringModelCreator.java:49)
	at de.embl.cba.tables.view.TableRowsTableView.lambda$null$20(TableRowsTableView.java:701)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tischi** [comment]
thanks. fixed. will upload to Fiji soon.
